spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: xx200200



